name: Sparrownest
favicon: null
layout_spectrum: 0.7601125717628747
typography_spectrum: 0.5778995319269598
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.10770083754323423
  lightness: 0.09989445609971881
  saturation: 0.21097956830635667
  rhythmicContrast: 0.0464400346390903
purpose: []
